Input from a tty

./Bin/create-model-lame.x:   lin7@cees-gpu   Mon Aug  3 15:24:51 2015
		sets next: in="/data/lin7/create-model-lame.x@ewzD0r"
		From par: nz=300
		From par: oz=0
		From par: dz=4
		From par: nx=300
		From par: ox=0
		From par: dx=4
		From par: water=no
		From par: waterz=0
		From par: waterlambda=2.25e+09
		From par: watermu=0
		From par: waterrho=1000
		From par: lvl=no
		From par: nlvl=0
		From par: lvlvz1=0
		From par: lvlvz2=0
		From par: lvllambda=-1
		From par: lvlmu=0
		From par: lvlrho=1000
		From par: lambda1=5.12e+09
		From par: mu1=2.88e+09
		From par: rho1=2000
		From par: vz=0
		From par: ref=yes
		From par: z1=200
		From par: thick=100
		From par: lambda2=6e+09
		From par: mu2=4e+09
		From par: rho2=2500
		From par: anom=no
		From par: anomz=0
		From par: anomx=0
		From par: anomsigma=0
		From par: anomstr=0
		From par: anomrho=0
		From par: anomlambda=0
		From par: anommu=0
		From par: circle=no
		From par: circlez=0
		From par: circlex=0
		From par: circleradius=0
		From par: circlelambda=-1
		From par: circlemu=-1
		From par: circlerho=-1
		n1=300
		o1=0
		d1=4
		n2=300
		o2=0
		d2=4
		label1="z"
		label2="x"
		data_format="xdr_float"



Smooth:   lin7@cees-gpu   Mon Aug  3 15:24:51 2015
		sets next: in="/data/lin7/Smooth@Wz2BOs"
	Data smoothed with tridiagonal solver leaky().
		Data smoothed with: rect1=20
		Data smoothed with: rect2=20
		Data smoothed with: rect3=1
		data_format="xdr_float"

